### ISSUE TITLE
registerIRPrivateBundles on server only

### ISSUE THREAD

**Issue by joshua1** [numtel/meteor-lazy-bundles#2]
@numtel  Am trying to use this package and my route definitions though in shared location are client side routes. I keep getting this error `Uncaught ReferenceError: registerIRPrivateBundles is not defined`. I checked the package source and saw it was exported server side only. why is that and how can i use it given my setup.
Thanks

**Comment by numtel** [comment]
The routes for your private bundles are server side routes only. The specific URL is requested from the browser directly. You do not need to change your client side routes, add the server-side code to your application to install the iron router plugin.
